
export enum lifeProblemsRecommendations {
    RECOMMENDATION_HOUSING_RESIDENCE = 'For concerns about residence, we recommend you contact Residence'
    // tslint:disable-next-line:max-line-length
    + 'services (<a href="http://www.uwindsor.ca/residence/">http://www.uwindsor.ca/residence/</a>, <strong>519-253-3000 ext. 3279</strong>, <strong>resservices@uwindsor.ca</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_HOUSING_OFF_CAMPUS = 'For concerns related to living off campus, we recommend you check this website for FAQs (<a href="http://www.uwindsor.ca/success/off-campus-housing/299/im-living-campus">http://www.uwindsor.ca/success/off-campus-housing/299/im-living-campus</a>). You might also check out Windsor Essex Community Housing Corporation for assistance finding housing, for individuals with disabilities or those in need, (<a href="https://www.wechc.com/">https://www.wechc.com/</a>, <strong>519-254-1681</strong>) or the Downtown Mission of Windsor, if you need emergency shelter (<a href="https://www.downtownmission.com">https://www.downtownmission.com</a>, <strong>519-973-5573</strong>, <strong>info@downtownmission.com</strong>)',
    RECOMMENDATION_LEGAL = 'For legal issues, we recommend you contact Community Legal Aid'
    + '(<a href="http://communitylegalaidwindsor.com/">http://communitylegalaidwindsor.com/</a>, <strong>519-253-7150</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_LIFE_PROBLEM_FINANCE = 'For financial problems, we recommend you contact student awards and financial aid (<a href="http://www.uwindsor.ca/studentawards/304/office-location-and-hours">http://www.uwindsor.ca/studentawards/304/office-location-and-hours</a>, <strong>519-253-3000 ext. 3300</strong>, <strong>award1@uwindsor.ca</strong>). You might also check out the Financial Fitness Centre, a not-for-profit credit counselling service (<a href="http://www.financialfitnesswindsor.ca/">http://www.financialfitnesswindsor.ca/</a>, <strong>1-877-777-9218</strong>, <strong>appointment@financialfitnesswindsor.ca</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_INTERPERSONAL_RESIDENCE = 'For interpersonal issues, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact peer mentoring, where trained peer mentors offer peer counselling to other students,  (<a href="http://www.uwsa.ca/uwsa-services/psc/">http://www.uwsa.ca/uwsa-services/psc/</a> <strong>519-253-3000 ext. 4551</strong>, <strong>psc@uwindsor.ca</strong>) ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_INTERPERSONAL_OFF_CAMPUS = 'For interpersonal issues, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481)</strong>, or the Canadian Mental Health Association (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>).',
    RECOMMENDATION_INTERPERSONAL_TELEPHONE = 'For interpersonal issues, we recommend you call Good2Talk, a free telephone'
    + 'support service for Ontario university students <strong>(1-866-925-5454)</strong>',
    RECOMMENDATION_INTERPERSONAL_WEB = 'For interpersonal issues, we recommend Big White Wall,'
    + 'an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>)'
    // tslint:disable-next-line:max-line-length
    + 'or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_SEXUAL_ABUSE = 'To report sexual assault, abuse or harassment, you can go to the University of Windsor sexual misconduct office (<a href="http://www.uwindsor.ca/sexual-assault/">http://www.uwindsor.ca/sexual-assault/</a>, <strong>519-253-3000 ext. 4550</strong>, <strong>dustyj@uwindsor.ca</strong>), the Windsor police (<a href="https://www.police.windsor.on.ca/services/reporting/Pages/Report-Sexual-Assault.aspx">https://www.police.windsor.on.ca/services/reporting/Pages/Report-Sexual-Assault.aspx</a>, <strong>519-258-6111</strong>) or the Windsor Sexual Assault crisis centre’s 24-hour crisis line (<strong>519-253-9667</strong>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_SEXUAL_ABUSE_RESIDENCE = 'For concerns related to sexual harassment, abuse or assault, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact the University of Windsor sexual misconduct office, (<a href="http://www.uwindsor.ca/sexual-assault/">http://www.uwindsor.ca/sexual-assault/</a>, <strong>519-253-3000 ext. 4550</strong>)',
    RECOMMENDATION_SEXUAL_ABUSE_OFF_CAMPUS = 'For concerns related to sexual harassment, abuse or assault,'
    + 'we recommend you contact the Windsor Sexual assault crisis centre, where you can receive'
    + 'counselling (<a href="https://saccwindsor.net/">https://saccwindsor.net/</a>, <strong>519-253-3100</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_SEXUAL_ABUSE_TELEPHONE = 'For concerns related to sexual harassment, abuse or assault, we recommend you contact the Windsor Sexual Assault crisis centre’s 24-hour crisis line (<strong>519-253-9667</strong>) or the Assaulted Womens’ Helpline (<strong>1-866-863-0511</strong>). For concerns related to sexual harassment, abuse or assault, we recommend you call Support Services for male survivors (<a href="https://www.attorneygeneral.jus.gov.on.ca/english/ovss/male_support_services/">https://www.attorneygeneral.jus.gov.on.ca/english/ovss/male_support_services/</a> , <strong>1-866-887-0015</strong>) ',
    RECOMMENDATION_SEXUAL_ABUSE_WEB = 'For concerns related to sexual harassment, abuse or assault,'
    // tslint:disable-next-line:max-line-length
    + 'we recommend you check out Draw the Line’s website (<a href="http://www.draw-the-line.ca/index.html">http://www.draw-the-line.ca/index.html</a>)',
    RECOMMENDATION_PHYSICAL_ASSAULT_REPORT = 'To report physical assault, abuse or threats, we recommend that you contact campus'
    // tslint:disable-next-line:max-line-length
    + 'police (<a href="http://www.uwindsor.ca/campuspolice/">http://www.uwindsor.ca/campuspolice/</a>, <strong>519-253-3000 ext. 1234</strong>) or Windsor Police Services ',
    RECOMMENDATION_PHYSICAL_ASSAULT_RESIDENCE = 'For concerns related to physical assault, abuse or threats, we recommend that you'
    // tslint:disable-next-line:max-line-length
    + 'contact, student counselling centre (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>) and campus police'
    + '(<a href="http://www.uwindsor.ca/campuspolice/">http://www.uwindsor.ca/campuspolice/</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_PHYSICAL_ASSAULT_OFFCAMPUS = 'For concerns related to physical assault, abuse or threats, we recommend you that you contact Windsor police services (<a href="https://www.police.windsor.on.ca/Pages/Home.aspx">https://www.police.windsor.on.ca/Pages/Home.aspx</a>, <strong>519-258-6111</strong>). (Display the following if respondent is female) You may also wish to contact Hiatus House, where you can receive counselling or shelter (<a href="https://www.hiatushouse.com/index.html">https://www.hiatushouse.com/index.html</a>, <strong>519-252-7781</strong>)',
    RECOMMENDATION_PHYSICAL_ASSAULT_TELEPHONE = 'For issues related to physical abuse, assault or threats, we recommend you call'
    // tslint:disable-next-line:max-line-length
    + 'the Canadian Resource Centre for Victims of Crime (<strong>1-877-232-2610</strong>) or the Ontario Victims Services support line (<strong>1-888-579-2888</strong>) ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_PHYSICAL_ASSAULT_WEB = 'For issues related to abuse, assault or threats, we recommend you contact the Canadian Resource Centre for Victims of Crime (<a href="https://crcvc.ca/">https://crcvc.ca/</a>) or the Ontario Victims Services website (<a href="http://www.attorneygeneral.jus.gov.on.ca/english/ovss/about.php">http://www.attorneygeneral.jus.gov.on.ca/english/ovss/about.php</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_GRIEF_RESIDENCE = 'For issues related to grief and loss, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact peer mentoring, where trained peer mentors offer peer counselling to other students,  (<a href="http://www.uwsa.ca/uwsa-services/psc/">http://www.uwsa.ca/uwsa-services/psc/</a> <strong>519-253-3000 ext. 4551</strong>, <strong>psc@uwindsor.ca</strong>) ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_GRIEF_OFF_CAMPUS = 'For issues related to grief and loss, we recommend you contact the Canadian Mental Health Association, where you may receive supportive grief counseling ( (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>) or contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>).',
    RECOMMENDATION_GRIEF_TELEPHONE = 'For issues related to grief and loss, we recommend you call Good2Talk, a free telephone support'
    + ' service for Ontario university students (<strong>1-866-925-5454</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_GRIEF_WEB = 'For issues related to grief and loss, we recommend Big White Wall, an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>), Bounce Back, an online program for managing mood and anxiety (<a href="https://bouncebackontario.ca/">https://bouncebackontario.ca/</a>) or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_PERSONAL_HEALTH = 'For issues related to personal health, we recommend that you contact Student Health Services <a href="http://www.uwindsor.ca/studenthealthservices/">http://www.uwindsor.ca/studenthealthservices/</a> , <strong>519-973-7002</strong>) or go to a walk-in clinic (<a href="http://www.uwindsor.ca/studenthealthservices/508/community-walk-clinics">http://www.uwindsor.ca/studenthealthservices/508/community-walk-clinics</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_DISCRIMINATION = 'For issues related to discrimination, we recommend that you contact the Student Counselling Centre (<a href="http://www.uwindsor.ca/studentcounselling/"></a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>), the Office of Human Rights, Equity and Accessbility (<a href="http://www.uwindsor.ca/faculty/recruitment/335/office-human-rights-equity-and-accessibility-ohrea">http://www.uwindsor.ca/faculty/recruitment/335/office-human-rights-equity-and-accessibility-ohrea</a>, <strong>519-253-3000 ext. 3400</strong>), Student accessibility services (<a href="http://www.uwindsor.ca/studentaccessibility/">http://www.uwindsor.ca/studentaccessibility/</a>, <strong>519-253-3000 ext. 6172</strong>, <strong>sas@uwindsor.ca</strong>). You may also wish to contact the Womxn’s Centre (CAW room 208), the Turtle island aboriginal centre (CAW room 179) or Campus pride centre (CAW room 260). Off-campus services that might be helpful include the Windsor Pride Community (<a href="www.windsorpride.com">www.windsorpride.com</a>, <strong>519-973-4656</strong>, <strong>executive.director@windsorpride.com</strong>), Windsor-Essex Trans Support (<a href="www.wetranssupport.ca">www.wetranssupport.ca</a>, <strong>226-674-4745</strong>, <strong>info@wetranssupport.ca</strong>) or the Southwest Ontario Aboriginal Health Access Centre (<a href="https://soahac.on.ca">https://soahac.on.ca</a> <strong>519-916-1755</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_FOOD = 'There is a free bus shuttle that runs every Tuesday, between 6 PM and 10 PM. The last bus departs from the Superstore at 8:45PM.The pickup locations start at Cartier Hall, Canterbury College, and then KFC at Bridge. The round-trip bus drops students off at the Real Canadian Superstore on Dougall, and continuously runs back and forth to the pick up locations. (<a href="http://www.uwindsor.ca/residence/grocery">http://www.uwindsor.ca/residence/grocery</a>). If you are in need, there is a campus food pantry in CAW (<a href="http://www.uwsa.ca/uwsa-services/campus-food-pantry/">http://www.uwsa.ca/uwsa-services/campus-food-pantry/</a>) and another at Iona college (<a href="http://www.uwindsor.ca/ionacollege/298/campus-food-bank">http://www.uwindsor.ca/ionacollege/298/campus-food-bank</a>).',
    RECOMMENDATION_GETTING_AROUND = 'If you have not picked up your free Transit Windsor bus pass, you can pick it up at the UWSA office.'
    // tslint:disable-next-line:max-line-length
    + 'You can find bus route maps and schedules at the Transit Windsor website (<a href="www.citywindsor.ca/transitwindsor">www.citywindsor.ca/transitwindsor</a>).'
}
export enum academicProblemRecommendations {
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_ACADEMIC = 'For concerns about your future career, we recommend that you consider Exploring Career Pathways (<a href="http://www.uwindsor.ca/science/421/exploring-career-pathways">http://www.uwindsor.ca/science/421/exploring-career-pathways</a>) or speak to your academic advisor (insert department-specific recommendation from list below). You may also wish to consult the Career Development and Experiential Learning service on campus (<a href="http://www.uwindsor.ca/career-development-experiential/">http://www.uwindsor.ca/career-development-experiential/</a> , <strong>519-253-3000 ext. 3895</strong>, <strong>careerservices@uwindsor.ca</strong>) or the Academic Advising Office (<a href="http://www.uwindsor.ca/success/advising">http://www.uwindsor.ca/success/advising</a>, <strong>519-253-3000 ext. 1414</strong>, <strong>advising@uwindsor.ca</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_ACADEMIC_TIME = 'If you are concerned about your workload and time management, we recommend that you contact the STEPS program (Skills to Enhance Personal Success) (<a href="http://www.uwindsor.ca/faculty/recruitment/359/skills-enhance-personal-success-steps">http://www.uwindsor.ca/faculty/recruitment/359/skills-enhance-personal-success-steps</a>, <strong>steps@uwindsor.ca</strong>). You could also contact MySci peer mentoring (<a href="https://www.uwinscisoc.com/mysci-mentorship">https://www.uwinscisoc.com/mysci-mentorship</a>) or Connecting4Success, a campus-wide mentoring program (<a href="http://www.uwindsor.ca/success/c4s">http://www.uwindsor.ca/success/c4s</a>). Other options for managing stress related to academic workload/time management would be Bounce Back, a program designed to support students who are struggling with post-secondary success (<a href="http://www.uwindsor.ca/success/bounceback">http://www.uwindsor.ca/success/bounceback</a>, <strong>bounceback@uwindsor.ca</strong>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_ACADEMIC_GRADES = 'For issues related to grades, we recommend SOS exam aid sessions (<a href="https://windsor.soscampus.com/">https://windsor.soscampus.com/</a>). For issues related to writing, you can contact the Writing support desk (<a href="http://www.uwindsor.ca/success/writingsupportdesk">http://www.uwindsor.ca/success/writingsupportdesk</a>). (If respondent identifies as 1st year undergrad only) For issues related to math and statistics, you can contact the Math and Stats Learning Centre ( <a href="http://www1.uwindsor.ca/math/math-and-stats-learning-centre">http://www1.uwindsor.ca/math/math-and-stats-learning-centre</a>). (If respondent identifies as 1st year undergrad only) For issues related to chemistry and physics, you can contact the Chemistry and Physics Resource Centre (<a href="http://www.uwindsor.ca/science/chemistry/486/undergraduate-resource-centre">http://www.uwindsor.ca/science/chemistry/486/undergraduate-resource-centre</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_ACADEMIC_PROF = 'If you are having a problem with the GA/TA, we recommend that you speak to the professor running the course. If you are having a problem with a professor, we suggest that you speak to the head of your department or (display the following if respondent identifies as an undergraduate) the Associate Dean of Undergraduate Studies (<strong>science@uwindsor.ca</strong>, <strong>519-253-3000 ext. 3009</strong>) or (display the following if respondent identifies as a graduate student) the Associate Dean of Graduate Studies (<strong>scienceadgsr@uwindsor.ca</strong>, <strong>519-253-3000 ext. 3009</strong>). If you are having a problem with a staff member, we suggest that you speak to the head of your department and/or the Dean of Science’s office (<strong>519-253-3000 ext. 3009</strong>). You may also wish to speak to Student accessibility services (<a href="http://www.uwindsor.ca/studentaccessibility/">http://www.uwindsor.ca/studentaccessibility/</a>, <strong>519-253-3000 ext. 6172</strong>, <strong>sas@uwindsor.ca</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_ACADEMIC_ANXEITY = 'For concerns about graduate or professional school, we recommend that you contact the Career Development and Experiential Learning service on campus (<a href="http://www.uwindsor.ca/career-development-experiential/">http://www.uwindsor.ca/career-development-experiential/</a> , <strong>519-253-3000 ext. 3895</strong>, <strong>careerservices@uwindsor.ca</strong>), the chair of graduate studies in your department of interest, the Associate Dean of Graduate studies in science (<strong>scienceadgsr@uwindsor.ca</strong>, <strong>519-253-3000 ext. 3009</strong>).'
}
export enum mentalHealthProblemRecommendations {
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_MOOD_RESIDENCE = 'For problems related to low mood, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact peer mentoring, where trained peer mentors offer peer counselling to other students,  (<a href="http://www.uwsa.ca/uwsa-services/psc/">http://www.uwsa.ca/uwsa-services/psc/</a> <strong>519-253-3000 ext. 4551</strong>, <strong>psc@uwindsor.ca</strong>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_MOOD_OFF_CAMPUS = 'For problems related to low mood, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>), or the Canadian Mental Health Association (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>). ',

    RECOMMENDATION_MENTAL_HEALTH_MOOD_TELE = 'For problems related to low mood, we recommend you call Good2Talk, a'
    + 'free telephone support service for Ontario university students (<strong>1-866-925-5454</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_MOOD_WEB = 'For problems related to low mood, we recommend Big White Wall, an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>), Bounce Back, an online program for managing mood and anxiety (<a href="https://bouncebackontario.ca/">https://bouncebackontario.ca/</a>) or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUICIDAL_RISK = 'If you are at risk of hurting or killing yourself, we recommend that you call Community crisis (<strong>519-973-4435</strong>), the 24 hour Crisis Service Canada line (<strong>1-833-456-4566</strong>, call <strong>911</strong> or go immediately to the 24/7 Walk-in Crisis Service at the Windsor Regional Hospital Emergency Department on 1030 Ouellette Ave. If is between the hours of 8:30am and 4:30pm, please go to CAW Room 293 or call <strong>519-253-3000 ext. 4616</strong>.',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUICIDAL_RESIDENCE = 'For suicidal thoughts, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUICIDAL_OFFCAMPUS = 'For suicidal thoughts, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>. You may also go to the Community Crisis Centre within the within the Transitional Stability Centre at Hotel Dieu Grace. They are open 8:00 a.m. to 8:00 pm seven days/week',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUICIDAL_TELE = 'For suicidal thoughts, we recommend that you call the Hotel Dieu Grace 24 hour Crisis Telephone Line (<strong>519-973-4435</strong>), the 24 hour Crisis Service Canada line (<strong>1-833-456-4566</strong>, Text 45645 between 4pm-12am) or Connex Ontario, a free telephone support service (<strong>1-866-531-2600</strong>, 24 hours/7 days a week).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUICIDAL_WEB = 'For suicidal thoughts or self-harm, we recommend the Ontario Association for Suicide Prevention (<a href="http://ospn.ca/">http://ospn.ca/</a>), the Canadian Association for Suicide Prevention (<a href="https://www.suicideprevention.ca/">https://www.suicideprevention.ca/</a>) or the Self-Injury Outreach and Support website (<a href="http://www.sioutreach.org">http://www.sioutreach.org</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANXIETY_RESIDENCE = 'For problems related to excessive worry, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact peer mentoring, where trained peer mentors offer peer counselling to other students,  (<a href="http://www.uwsa.ca/uwsa-services/psc/">http://www.uwsa.ca/uwsa-services/psc/</a> <strong>519-253-3000 ext. 4551</strong>, <strong>psc@uwindsor.ca</strong>) ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANXIETY_OFFCAMPUS = 'For problems related to excessive worry, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>), or the Canadian Mental Health Association ( (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANXIETY_TELE = 'For problems related to excessive worry, we recommend you call Good2Talk, a free telephone support service for Ontario university students (<strong>1-866-925-5454</strong>) or Connex Ontario, a free telephone support service (<strong>1-866-531-2600</strong>, 24 hours/7 days a week).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANXIETY_WEB = 'For problems related to excessive worry, we recommend Big White Wall, an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>), Bounce Back, an online program for managing mood and anxiety (<a href="https://bouncebackontario.ca/">https://bouncebackontario.ca/</a>), or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANGER_RESIDENCE = 'For problems related to anger or irritability, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact peer mentoring, where trained peer mentors offer peer counselling to other students,  (<a href="http://www.uwsa.ca/uwsa-services/psc/">http://www.uwsa.ca/uwsa-services/psc/</a> <strong>519-253-3000 ext. 4551</strong>, <strong>psc@uwindsor.ca</strong>) ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANGER_OFF_CAMPUS = 'For problems related to anger or irritability, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>), or the Canadian Mental Health Association ( (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANGER_TELE = 'For problems related to anger or irritability, we recommend you call Good2Talk, a free telephone support service for Ontario university students (<strong>1-866-925-5454</strong>) or Connex Ontario, a free telephone support service (<strong>1-866-531-2600</strong>, 24 hours/7 days a week).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_ANGER_WEB = 'For problems related to anger or irritability, we recommend Big White Wall, an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>) or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_EATING_RESIDENCE = 'For problems related to disordered eating, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>) or Student Health Services (<a href="http://www.uwindsor.ca/studenthealthservices/">http://www.uwindsor.ca/studenthealthservices/</a> , <strong>519-973-7002</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_EATING_OFF_CAMPUS = 'For problems related to disordered eating, we recommend you contact the Bulimia and Anorexia Nervosa Association (<a href="https://bana.ca/">https://bana.ca/</a>, <strong>1-855-969-5530</strong>) or the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_EATING_TELE = 'For problems related to disordered eating, we recommend you call the National Eating Disorder Information Centre (<a href="http://www.nedic.ca">http://www.nedic.ca</a> , from 9 a.m. to 9 p.m. EST/EDT: <strong>1-866-633-4220</strong>) or the Hopewell Eating Disorder Support Centre for one-on-one peer support (<strong>613-241-3428</strong> from Monday to Friday, 9 am to 5 pm)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_EATING_WEB = 'For problems related to disordered eating, we recommend you check out the Ontario Community Outreach Program for Eating Disorders (<a href="http://www.ocoped.ca">http://www.ocoped.ca</a>) or the National Eating Disorder Information Centre (<a href="http://www.nedic.ca">http://www.nedic.ca</a>). ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SLEEPING_RESIDENCE = 'For problems related to sleeping difficulties, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SLEEPING_OFF_CAMPUS = 'For problems related to sleeping difficulties, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>), or the Canadian Mental Health Association ( (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>) )',

    RECOMMENDATION_MENTAL_HEALTH_SLEEPING_TELE = 'For problems related to sleeping difficulties, we recommend you'
    + 'call Good2Talk, a free telephone support service for Ontario university students (<strong>1-866-925-5454</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SLEEPING_WEB = 'For problems related to sleeping difficulties, we recommend TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>) or the Canadian Sleep Society (<a href="https://css-scs.ca/">https://css-scs.ca/</a>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUBSTANCE_RESIDENCE = 'For problems related to overuse of alcohol, tobacco, gaming/Internet, gambling or other substances, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>) or Student Health Services (<a href="http://www.uwindsor.ca/studenthealthservices/">http://www.uwindsor.ca/studenthealthservices/</a> , <strong>519-973-7002</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUBSTANCE_OFF_CAMPUS = 'For problems related to overuse of alcohol, tobacco, gaming/Internet, gambling or other substances, we recommend you contact the Canadian Mental Health Association (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>) or the Hôtel Dieu Grace Healthcare Addiction Assessment and Outpatient Service (<strong>519-257-5220</strong>), the Hotel Dieu Grace Centre for Problem Gambling and Digital Dependency (<a href="https://www.hdgh.org/vgnetdependency">https://www.hdgh.org/vgnetdependency</a>,  <strong>519-254-2112</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUBSTANCE_TELE = 'For problems related to overuse of alcohol, tobacco, gaming/Internet, gambling or other substances, we recommend you call Connex Ontario, a free telephone support service (<strong>1-866-531-2600</strong>, 24 hours/7 days a week) or the Ontario Problem Gambling Helpline (<strong>1-866-531-2600</strong>). ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_SUBSTANCE_WEB = 'For problems related to overuse of alcohol, tobacco, gaming/Internet, gambling or other substances, we recommend you check out the Windsor-Essex Health Unit (<a href="https://www.wechu.org/chronic-disease/get-help-drug-alcohol-and-other-addictions">https://www.wechu.org/chronic-disease/get-help-drug-alcohol-and-other-addictions</a>). For problems related to overuse of Internet or gaming, we recommend you check out the Center for Internet and Technology Addiction (<a href="https://virtual-addiction.com/resources/">https://virtual-addiction.com/resources/</a>) or the Center for Addiction and Mental Health series on technology (<a href="http://www.camhx.ca/education/online_courses/mha101/youthandtechnology/Youth_and_Technology_.htm">http://www.camhx.ca/education/online_courses/mha101/youthandtechnology/Youth_and_Technology_.htm</a>). For problems related to gambling, we recommend you check out the Problem Gaming Institute of Ontario (<a href="http://www.problemgambling.ca/gambling-help/">http://www.problemgambling.ca/gambling-help/</a>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_BODY_IMAGE_RESIDENCE = 'For problems related to body image, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href= "http://www.uwindsor.ca/studentcounselling/"> http://www.uwindsor.ca/studentcounselling/ </a>, <strong>519-253-3000 ext. 4616</strong>, <a href="scc@uwindsor.ca">scc@uwindsor.ca</a>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact peer mentoring, where trained peer mentors offer peer counselling to other students,  (<a href="http://www.uwsa.ca/uwsa-services/psc/">http://www.uwsa.ca/uwsa-services/psc/</a> <strong>519-253-3000 ext. 4551</strong>, <a href="psc@uwindsor.ca">psc@uwindsor.ca</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_BODY_IMAGE_OFF_CAMPUS = 'For problems related to body image, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href=”http://www.wechc.org/teenhealth_about”> http://www.wechc.org/teenhealth_about</a> , <strong>519-253-8481</strong>), the Canadian Mental Health Association (<a href=”https://windsoressex.cmha.ca/programs-services/”>https://windsoressex.cmha.ca/programs-services/</a>,  <strong>519-255-7440</strong>, <a href=”info-referral@cmha-wecb.on.ca”> info-referral@cmha-wecb.on.ca</a> .) or the Bulimia and Anorexia Nervosa Association (<a href=”https://bana.ca/”>https://bana.ca/</a>, <strong>1-855-969-5530</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_BODY_IMAGE_TELE = 'For problems related to body image, we recommend you call Good2Talk, a free telephone support service for Ontario university students (<strong>1-866-925-5454</strong>) or Connex Ontario, a free telephone support service (<strong>1-866-531-2600</strong>, 24 hours/7 days a week)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_BODY_IMAGE_WEB = 'For problems related to body image, we recommend Big White Wall, an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>) or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_TARUMA_RESIDENCE = 'For problems related to traumatic symptoms, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>).',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_TARUMA_OFF_CAMPUS = 'For problems related to traumatic symptoms, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>), or the Canadian Mental Health Association ( (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_TARUMA_TELE = 'For problems related to traumatic symptoms, we recommend you call Good2Talk, a free telephone support service for Ontario university students (<strong>1-866-925-5454</strong>) or Connex Ontario, a free telephone support service (<strong>1-866-531-2600</strong>, 24 hours/7 days a week)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_TARUMA_WEB = 'For problems related to traumatic symptoms, we recommend the PTSD association of Canada’s website (<a href="http://www.ptsdassociation.com/">http://www.ptsdassociation.com/</a>), the Lifeline Canada Foundation (<a href="https://thelifelinecanada.ca/resources/ptsd/">https://thelifelinecanada.ca/resources/ptsd/</a>), Big White Wall, an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>) or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_LONELINESS = 'If you would like to meet other students in science, we recommend the Science society, USci network programs such as Science Meets Art or Women in Science (insert link to new website when it becomes available), science outreach groups (<a href="https://outreach.letstalkscience.ca/uwindsor.html">https://outreach.letstalkscience.ca/uwindsor.html</a>) or your departmental student club. If you would like to meet other students who may share common interests, we recommend consulting the list of student clubs at the University of Windsor (<a href="https://www.campusvibe.ca/campusvibe/groups/b3dec320-64b6-413d-bb5e-dcd3afa78737">https://www.campusvibe.ca/campusvibe/groups/b3dec320-64b6-413d-bb5e-dcd3afa78737</a>) or checking out a student wellness event (<a href="http://www.uwindsor.ca/studentexperience/wellness/events">http://www.uwindsor.ca/studentexperience/wellness/events</a>, <a href="http://www.uwindsor.ca/studentexperience/wellness/take-the-moment">http://www.uwindsor.ca/studentexperience/wellness/take-the-moment</a>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_LONELINESS_RESIDENCE = 'For problems related to loneliness, homesickness or isolation, we recommend you contact the student counselling centre, where you can receive free counseling from trained mental health professionals, (<a href="http://www.uwindsor.ca/studentcounselling/">http://www.uwindsor.ca/studentcounselling/</a>, <strong>519-253-3000 ext. 4616</strong>, <strong>scc@uwindsor.ca</strong>). We also offer several wellness groups on campus (<a href="http://www.uwindsor.ca/studentcounselling/grouptherapy">http://www.uwindsor.ca/studentcounselling/grouptherapy</a>). You can also contact peer mentoring, where trained peer mentors offer peer counselling to other students,  (<a href="http://www.uwsa.ca/uwsa-services/psc/">http://www.uwsa.ca/uwsa-services/psc/</a> <strong>519-253-3000 ext. 4551</strong>, <strong>psc@uwindsor.ca</strong>) ',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_LONELINESS_OFF_CAMPUS = 'For problems related to loneliness, homesickness or isolation, we recommend you contact the Teen Health Centre, where you can receive free individual or group counseling, (<a href="http://www.wechc.org/teenhealth_about">http://www.wechc.org/teenhealth_about</a>, <strong>519-253-8481</strong>), or the Canadian Mental Health Association ( (<a href="https://windsoressex.cmha.ca/programs-services/">https://windsoressex.cmha.ca/programs-services/</a> ,  <strong>519-255-7440</strong>, <strong>info-referral@cmha-wecb.on.ca</strong>',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_LONELINESS_TELE = 'For problems related to loneliness, homesickness or isolation, we recommend you call Good2Talk, a free telephone support service for Ontario university students (<strong>1-866-925-5454</strong>)',
    // tslint:disable-next-line:max-line-length
    RECOMMENDATION_MENTAL_HEALTH_LONELINESS_WEB = 'For problems related to loneliness, homesickness or isolation, we recommend Big White Wall, an online mental health and wellbeing service (<a href="BigWhiteWall.ca">BigWhiteWall.ca</a>) or TAO, an online library of mental health resources (<a href="http://www.uwindsor.ca/studentexperience/358/tao">http://www.uwindsor.ca/studentexperience/358/tao</a>)'
}
